version: "3"

services:
  app:
    environment:
      DB_HOST: db
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/opt/app
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
